#!/bin/bash

prompt="Adjust your display configuration, then:\\nLayout > Save As > ~/.screenlayout/multihead.sh"
mkdir -p $HOME/.screenlayout
zenity --question --text="$prompt" --title="Important" --ok-label="Next" --cancel-label="Cancel" && \
echo "$prompt" && \
arandr && \
bash $HOME/.screenlayout/multihead.sh
