#!/bin/bash

mkdir -p $HOME/.screenlayout
zenity --question --text="Adjust your display configuration, then:\\nLayout > Save As > ~/.screenlayout/multihead.sh" --title="Important" --ok-label="Next" --cancel-label="Cancel" && \
arandr && \
bash $HOME/.screenlayout/multihead.sh
