#!/bin/bash

if git rev-parse --absolute-git-dir 2>/dev/null; then
    cmd="tig"
else
    cmd="GIT_DIR=\"$HOME/.dotfiles/.git\" GIT_WORK_TREE=\"$HOME/.dotfiles\" tig"
fi
if [[ $1 == "s" ]]; then
    eval "$cmd status"
    elif [[ $1 == "a" ]]; then
    eval "$cmd --all"
    elif [[ $1 == "r" ]]; then
    eval "$cmd refs"
    elif [[ $1 == "y" ]]; then
    eval "$cmd stash"
else
    eval "$cmd"
fi
