#!/bin/bash

# Convenience script for finding a tmux session by name and attaching to it.
# The session will be created if it doesn't exist, and a predefined layout will
# be applied. An initial working directory can be specified as the second argument.
#
# ex.
#  tmuxa mysession ~/projects/myproject

if [ $# -eq 1 ] || [ $# -eq 2 ]; then
    session_name="$1"
else
    echo "usage: tmuxa <session-name> [<dir>]"
    exit 1
fi

if [ -z "$2" ]; then
    cd $HOME
else
    cd $2
fi

p2s="tmux-pane-view --pane-to-session"

# If the session doesn't exist, create it and set up the layout
if ! tmux has-session -t "$1" 2>/dev/null; then
    tmux new-session -s "$1" $p2s \; \
    split-window -v -l "90%" $p2s \; \
    select-pane -t 0 \; \
    split-window -h $p2s \; \
    split-window -h $p2s \; \
    select-pane -t 3
fi

# Otherwise, attach to the session
tmux attach -t "$session_name"
