#!/bin/bash

dir="$HOME/.config/alacritty"
[[ ! -d "$dir" ]] && \
notify-send "Directory $dir does not exist" && exit 0

for path in "$dir"/*.toml; do
    [[ ! -f "$path" ]] && continue

    if [ "$1" = "--on" ]; then
        new_val=0.4
    elif [ "$1" = "--off" ]; then
        new_val=1
    else 
        opacity=$(awk -F '=' '/^opacity/ {gsub(/[[:space:]]/, "", $2); print $2; exit}' "$path")
        case $opacity in
            1)
                new_val=0.4
            ;;
            *)
                new_val=1
            ;;
        esac
    fi
    echo $new_val

    target=$(readlink -f "$path")
    if [[ -z "$target" ]]; then
        echo "Error: Symlink target does not exist or is invalid for $path."
        continue
    fi

    sed -i -- 's/opacity = [^ ]*/opacity = '"$new_val"'/' "$target"
done
