#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
pipe=$dir/kp-status
if [[ ! -p $pipe ]]; then
    mkfifo $pipe
fi

if pgrep -x "kp" > /dev/null || [[ "$1" = "--off" ]]; then
    sudo pkill -x kp
else
    kp >/dev/null &
fi

get-kp-status
