#!/bin/bash

if [ "$#" -gt 1 ]; then
    echo "Usage: $0 [<application_name>]"
    exit 1
fi

if [ $# -eq 1 ]; then
    sink=$(get-pulseaudio-sink "$1")
    pactl get-sink-volume $sink | grep -oh "[0-9]*%" | head -n 1 | sed 's/%//'
else
    pactl get-sink-volume @DEFAULT_SINK@ | grep -oh "[0-9]*%" | head -n 1 | sed 's/%//'
    
    # amixer equivalent:
    # amixer -M get Master | tail -n 1 | awk -F 'Playback ' '{print $2}' | awk -F ' \\[' '{print $1}'
fi
