#!/bin/bash

#======================================================
print_usage() {
    echo "Usage: $0 <dev>"
}
if [ "$#" -ne 1 ]; then
    print_usage
    exit 1
fi
#------------------------------------------------------

v=$(sensors | grep $1 | awk -F " " '{print $2}')
if [[ ! -e $v ]]; then
    echo $(sensors | grep $1 | awk -F " " '{print $2}')RPM
    echo "$v"RPM
fi
